Add build version report
wavefrontHQ/wavefront-pyformance pull request #35
Opened 2020-10-02 16:44 UTC by xshipeng

2020-10-02 23:23 UTC, haosong commented on README.md
> +Python ~~2.7+~~ and Python 3.x are supported.
let's just keep `Python 3.x are supported.`

2020-10-02 23:30 UTC, haosong approved these changes

2020-10-03 00:07 UTC, hanwavefront approved these changes

2020-10-06 18:43 UTC, hanwavefront approved these changes
LGTM, thanks

2020-10-06 21:14 UTC, haosong commented
Update the License as well

2020-10-06 21:16 UTC, haosong requested changes

2020-10-06 21:16 UTC, haosong commented on setup.py
> +    version='1.2.0',
update license as well

2020-10-08 20:50 UTC, haosong approved these changes

2020-10-08 21:50 UTC, sushantdewan123 approved these changes

2020-10-08 21:50 UTC, merged